### ISSUE TITLE
Ex 3: Clarifications about formula

### ISSUE THREAD

**Issue by meyerdav** [Digital-Humans-23/a4#4]
Based on the README, I have two questions regarding the provided formulas: Firstly what does speed_t means. Does it mean to replace T with t or to calculate the difference only for t and t-1. Secondly, why do we divide by T-2 instead of T-1 in the definition of s_speed?

**Comment by xiyichen** [comment]
Have you figured it out? I was wondering the same

**Comment by zkf1997** [comment]
The equation in Ex. 3 uses the central difference (you may check https://math.stackexchange.com/a/888280/1123371) to calculate the velocity for the frames [1, T-2]. Since we use central difference, we ignore the first frame 0, and the last frame T-1. Thus we have T-2 frames in total.
The definition of speed^t is the L2 norm of the velocity at frame t.

**Comment by xiyichen** [comment]
In this case shouldn't s_speed be summed up to t=T-2 instead of t=T-1, since the last frame is ignored?

**Comment by zkf1997** [comment]
yes, there was a typo in the equation and is now corrected in the readme. It should sum up to T-2.
